spring:
  netty:
    leak-detection: paranoid

############################### Turms ###############################

turms:
  ai-serving:
    admin-api:
      debug:
        enabled: true
  logging:
    console:
      enabled: true