spring:
  netty:
    leak-detection: paranoid

############################### Turms ###############################

turms:
  gateway:
    admin-api:
      debug:
        enabled: true
  logging:
    console:
      enabled: true
  plugin:
    js:
      debug:
        enabled: true