spring:
  netty:
    leak-detection: paranoid

############################### Turms ###############################

turms:
  cluster:
    connection:
      server:
        port-auto-increment: true
    shared-config:
      mongo:
        uri: mongodb://localhost:27017/turms-config-dev
  logging:
    console:
      enabled: true
  plugin:
    js:
      debug:
        enabled: true
  service:
    admin-api:
      debug:
        enabled: true
    client-api:
      logging:
        included-notification-categories:
          - category: all
    fake:
      enabled: true
    message:
      check-if-target-active-and-not-deleted: false
    mongo:
      admin:
        uri: mongodb://localhost:27017/turms-dev
      user:
        uri: mongodb://localhost:27017/turms-dev
      group:
        uri: mongodb://localhost:27017/turms-dev
      conversation:
        uri: mongodb://localhost:27017/turms-dev
      message:
        uri: mongodb://localhost:27017/turms-dev
        tiered-storage:
          enabled: true
          tiers:
            hot:
              days: 30
              shards:
                - shard01
            warm:
              days: 60
              shards:
                - shard01
            cold:
              days: 270
              shards:
                - shard01
            frozen:
              shards:
                - shard01
turms-plugin:
  minio:
    retry:
      enabled: false