name: Test Terraform

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Init - Playground
        working-directory: './terraform/alicloud/playground'
        run: terraform init

      - name: Validate - Playground
        working-directory: './terraform/alicloud/playground'
        run: terraform validate

      - name: Verify Format - Playground
        working-directory: './terraform/alicloud/playground'
        run: terraform fmt -diff -check

      - name: Init - Cluster
        working-directory: './terraform/alicloud/cluster'
        run: terraform init

      - name: Validate - Cluster
        working-directory: './terraform/alicloud/cluster'
        run: terraform validate

      - name: Verify Format - Cluster
        working-directory: './terraform/alicloud/cluster'
        run: terraform fmt -diff -check