name: Test turms-client-swift

on: [ push, pull_request ]

jobs:
  test:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Build
        working-directory: turms-client-swift
        run: swift build -v

#      - name: Test
#        working-directory: turms-client-swift
#        run: swift test -v